### ISSUE TITLE
Release of v 1.2

### ISSUE THREAD

**Issue by scarlehoff** [N3PDF/vegasflow#59]
### To Do

- [x] Log control (PR #57)
- [x] Dask / cluster distribution (PR #55)
- [x] Pineappl example (PR #56)
- [x] Seed
- [x] Update the example target in setup.py
- [x] Prepare changelog

### Changelog

The version 1.2 brings some improvements, the most outstanding being
- Fine grained log control  #57 [[docs](https://vegasflow.readthedocs.io/en/latest/how_to.html#verbosity)].
- Distribution of jobs using [dask](https://dask.org/) #55 [[docs](https://vegasflow.readthedocs.io/en/latest/how_to.html#running-in-distributed-systems)].

We have also included several new use cases
- pineappl integration [[example](https://github.com/N3PDF/vegasflow/blob/master/examples/example_pineappl.py)].
- slurm distribution [[example](https://github.com/N3PDF/vegasflow/blob/master/examples/cluster_dask.py)].

Minor improvements of version 1.2 are
- Keyword `simplify_signature` #58 [[docs](https://vegasflow.readthedocs.io/en/latest/how_to.html#improving-results-by-simplifying-the-integrand)].
- `VegasFlow`, `vegas_wrapper`, `MonteCarloFlow`, `int_me`, `float_me` can be imported from `vegasflow`, ex. 
```python
from vegasflow import VegasFlow
```
-  The base type for float (`DTYPE`) and int (`DTYPEINT`) can be controlled with environment variables #58 [[docs](https://vegasflow.readthedocs.io/en/latest/how_to.html#environment)].
- Adds the utility function `generate_condition_function` #60 [[docs](https://vegasflow.readthedocs.io/en/latest/how_to.html#generate-conditions)].
- The integrators now have the `set_seed` method for seeding the random number generator [[docs](https://vegasflow.readthedocs.io/en/latest/how_to.html#seeding-the-random-number-generator)].

Let me know if I'm forgetting anything.

**Comment by scarlehoff** [comment]
I'll make the release tomorrow once the proceedings is out so I can link to it in the release notes.

**Comment by scarrazza** [comment]
Great, sounds and looks good.
